### ISSUE TITLE
zmq install issue with orbital_optimization plugin

### ISSUE THREAD

**Issue by bavramidis** [Ydrnan/qp_plugins_damour#9]
Hello,

I have been trying to create a qp2 singularity with the orbital_optimization plug in by following the instructions listed within https://github.com/Ydrnan/qp_plugins_damour/tree/master/orbital_optimization . 

I am using the following .def and .sh files: 
[qp2_install.sh.txt](https://github.com/Ydrnan/qp_plugins_damour/files/11204350/qp2_install.sh.txt)
[qp2_pure.def.txt](https://github.com/Ydrnan/qp_plugins_damour/files/11204352/qp2_pure.def.txt)

There is no issue in installing the qp2 master branch as I am able to create a qp2 singularity by running just the following in the install.sh file:
```
#!/bin/bash

set -e
set -x

git clone https://github.com/QuantumPackage/qp2 --branch=dev

cd qp2
source quantum_package.rc
./configure -i all
./configure -c ./config/gfortran_avx.cfg
make
```
The error seems to occur after the first ninja command within the trust_region  block in the .sh file.

It is interesting to note that when looking at the build output file, zmq as well as all the other packages needed for qp2 are listed as being installed. Searching 'opam update' within the build output file will show this. 

[output_1.txt](https://github.com/Ydrnan/qp_plugins_damour/files/11204456/output_1.txt)

I also reference a perhaps similar issue, here: https://github.com/QuantumPackage/qp2/issues/180 , however the error in this issue is slightly different.

If one could advise as to what might work in order to get around this error and create a singularity with the orbital_optimization plug in, it would be greatly appreciated.

Thanks, 
Ben

**Comment by Ydrnan** [comment]
Hello @bavramidis ,

Can you try to build the container without the following lines in the def file:
    apt install -y ninja-build
    apt install -y ocamlbuild
    apt install -y ocaml-findlib
    apt install -y libcryptokit-ocaml
    apt install -y libcryptokit-ocaml-dev
    apt install -y libzmq3-dev
    apt install -y libzmq5

I think the problem will be solved if you replace that by the dependencies contained by qp2.
In addition, the dev branch of qp2 should not be used anymore. You can use the master branch that has been merge recently or the dev-stable branch.

I hope it will fix the problem,
Yann

**Comment by bavramidis** [comment]
Hello @Ydrnan ,

Thank you for the prompt response. I have removed the above lines from the .def file, and used a dev-stable branch for qp2 installation, as you have suggested. 

I re-attach the .def and .sh files used in building the singularity. 
[qp2_pure_alt.def.txt](https://github.com/Ydrnan/qp_plugins_damour/files/11205301/qp2_pure_alt.def.txt)
[qp2_install.sh.txt](https://github.com/Ydrnan/qp_plugins_damour/files/11205302/qp2_install.sh.txt)

Please see most recent build output, given the changes you have suggested. 
[output_2.txt](https://github.com/Ydrnan/qp_plugins_damour/files/11205303/output_2.txt)

The error is now one of ocamlfind, even though this library is reported to be installed given the qp2 branch part of the singularity build. If one searches 'opam update' within the output file, all the necessary packages are explicitly installed. 

This ocamlfind error was previously encountered in the building of the singularity, and was solved by adding the above line(s) you have mentioned to take out, respectfully. 

Based on this, the issue seems to be one with respect to the plug in. 


Ben

**Comment by Ydrnan** [comment]
Perfect, the installation of qp2 seems to be clean. 
Concerning the error, it seems weird for me, I was not expecting this kind of error. Can you try with dev branch instead of the master for my plugin ?

Yann

**Comment by bavramidis** [comment]
Hello @Ydrnan ,

If I change the branch from branch=dev-stable to simply branch=dev, or if I use branch = master, the same error as that seen in output_2.txt, above, persists.

Ben

**Comment by Ydrnan** [comment]
Hello,

I think I found the problem, can you put the source quantum_package.rc after the ./configure -c.
And just to be sure, can you add a line to source qp2 before the ninja command in the plugin installation ?

Yann

**Comment by bavramidis** [comment]
Hello @Ydrnan,

I have found that the following .sh and .def files build the singularity without error. 

[qp2_install_alt.sh.txt](https://github.com/Ydrnan/qp_plugins_damour/files/11326170/qp2_install_alt.sh.txt)
[qp2_pure_alt_2.def.txt](https://github.com/Ydrnan/qp_plugins_damour/files/11326172/qp2_pure_alt_2.def.txt)


Thank you for your help with this.

Ben
